### ISSUE TITLE
galeforce_1.default is not a constructor

### ISSUE THREAD

**Issue by hemmoleg** [bcho04/galeforce#13]
Hey,

I'd realy like to use this. However when I try to create a new instace of the GaleforceModule I get the error `galeforce_1.default is not a constructor`

I alreay tried adding `"esModuleInterop": true,` to my tsconfig. But it didnt help. 
I am importing the module like so `import GaleforceModule from "galeforce";`
Here is my tsconfig.json:
```{
  "compileOnSave": false,
  "compilerOptions": {
    "baseUrl": "./",
    "outDir": "./dist/out-tsc",
    "forceConsistentCasingInFileNames": true,
    "strict": true,
    "noImplicitOverride": true,
    "noPropertyAccessFromIndexSignature": true,
    "esModuleInterop": true,
    "noImplicitReturns": true,
    "noFallthroughCasesInSwitch": true,
    "sourceMap": true,
    "declaration": false,
    "downlevelIteration": true,
    "experimentalDecorators": true,
    "moduleResolution": "node",
    "importHelpers": true,
    "target": "es2017",
    "module": "commonjs",
    "lib": [
      "es2020",
      "dom"
    ],
    "allowSyntheticDefaultImports": true,
  },
  "angularCompilerOptions": {
    "enableI18nLegacyMessageIdFormat": false,
    "strictInjectionParameters": true,
    "strictInputAccessModifiers": true,
    "strictTemplates": true
  }
}

**Comment by bcho04** [comment]
Hey @hemmoleg! Thanks for opening an issue. I'm having trouble replicating your error on my computer, as everything seems to be working fine with the following code on version `0.5.1`:

```typescript
import GaleforceModule from 'galeforce';

const galeforce = new GaleforceModule({
  'riot-api': {
    key: 'RGAPI-xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx',
  },
});
```

Would you be able to provide an example code snippet that raises the error, as well as the console output from the program? Thanks!

**Comment by hemmoleg** [comment]
Hey bcho04,

thank you for your quick reply. I have set up a repo where you can check out the code [here](https://github.com/hemmoleg/LoLStatsEF/tree/galeforceError)
See the index.ts file line 98 for how I initialize galeforce. Also have a look at my tsconfig.json file since my guess is that most likely something is wrong with that file.

**Comment by bcho04** [comment]
@hemmoleg,

I've taken a look at your source files and `tsconfig.json` and still can't seem to find the issue—when I initialize Galeforce in an async method it still works without erroring, and nothing about your `tsconfig` seems to be wrong at first glance. Can you try initializing directly from the command line like this?

```javascript
const GaleforceModule = require('galeforce');
const galeforce = new GaleforceModule();
```

**Comment by hemmoleg** [comment]
If I use the require instead of the import synatx it works. However what I found is that when using require there is no autocomplete in my ide (vs code) which is something I cant realy live without.

using import
![grafik](https://user-images.githubusercontent.com/32867143/142839225-47e7d4e5-24c8-40b3-bf4f-54b4aa16c48f.png)

using require
![grafik](https://user-images.githubusercontent.com/32867143/142839354-83107c73-d9de-4a11-ba01-87ccc0b52bdb.png)

I am no expert on these things but I think the issue has something to do with how you export the GaleforceModule. Maybe using `export default` could help?

**Comment by bcho04** [comment]
@hemmoleg — Currently the export in `/src/index.ts` is done with Typescript's `export =`:

```typescript
// taken from /src/index.ts

class Galeforce = {
    /* ... */
}

declare namespace Galeforce {
    /* ... */
}

export = Galeforce;
```

Perhaps you could try importing with `import GaleforceModule = require('galeforce')`?

**Comment by hemmoleg** [comment]
Using `import GaleforceModule = require('galeforce')` did the trick! I didnt even know that you could also do it this way.
Thanks for you help! :D
