### ISSUE TITLE
Module not found: Can't resolve 'console'

### ISSUE THREAD

**Issue by Huynheddie** [bcho04/galeforce#14]
**Description**
I set up my project using create-react-app and installed Galeforce, but when I try to import the package I get an error in the terminal: `Module not found: Can't resolve 'console' in 'D:\Projects\LoLTest\node_modules\ts-node\dist'`. 

**Reproduction Steps**
1. Create a new project by running the command `npx create-react-app LoLTest`
2. In the project directory, install Galeforce by running `npm i galeforce`
3. In the `App.js` file, import Galeforce using the following code: 
`import GaleforceModule from 'galeforce';`
4. Run `npm start` and the page will fail to display due to the compile error described above

**Specifications (please complete the following information):**
 - OS: Windows

**Comment by bangingheads** [comment]
JavaScript libraries like these are meant to be ran in the back end on node.js, not compiled into the front end like React.

If you were to use it on the front end you would be exposing your API key to everyone which is against Riot's developer policies as well as someone could get your key blacklisted.

**Comment by bcho04** [comment]
Going to resolve this as I don't think this is a fixable issue at the moment. Will see what I can do about this in the future though.
