### ISSUE TITLE
Requests hang when cache set to redis

### ISSUE THREAD

**Issue by xEcEz** [bcho04/galeforce#21]
**Description**
When trying to make any request, the request will hang if the client's cache is set to redis.

**Reproduction Steps**
1. Set rate limit cache to use redis 
2. Make any request to Riot's API

**Expected/Actual behavior**
The client to connect properly to the redis cache and execute the requests.

**Additional Information**
Here is the config I use:

```
{
  'riot-api': { key: 'XXXXXXXX' },
  'rate-limit': {
    type: 'bottleneck',
    cache: {
      type: 'redis',
      uri: 'redis://127.0.0.1:6379',
      'key-id': 'galeforce'
    },
    options: {
      intervals: [Object],
      'max-concurrent': null,
      'min-time': 0,
      'retry-count-after-429': 3
    }
  },
  debug: [ 'all' ]
}
```

Note that when setting the cache to `internal`, everything runs fine. Also, my redis server (`Redis version=5.0.8, bits=64`) is running and accessible through the passed URI. I've also tried setting the database in the URI as follows: `redis://127.0.0.1:6379/0`, but that didn't help.

**Comment by bcho04** [comment]
Should be fixed in 0.6.0.
