### ISSUE TITLE
Missing unit tests for the val-match-v1 endpoint

### ISSUE THREAD

**Issue by bcho04** [bcho04/galeforce#6]
Currently missing unit tests for the associated DTOs to the `val-match-v1` endpoint due to a lack of sample match data.

**Comment by bangingheads** [comment]
@bcho04 What would you like for sample match data?

**Comment by bcho04** [comment]
@bangingheads I don't have access to any of the `/val/match/v1` endpoints with my developer key, so I was wondering if I could get sample data for these endpoints so that I could test some DTO interfaces:
- `/val/match/v1/matches/{matchId}`
- `/val/match/v1/matchlists/by-puuid/{puuid}`
- `/val/match/v1/recent-matches/by-queue/{queue}`

**Comment by bangingheads** [comment]
Here's 5 responses from each endpoint:

https://gist.github.com/bangingheads/ef3a28500a1518512381a469cced64cc

Let me know if you need anything else

**Comment by bcho04** [comment]
Resolved in [0.5.1](https://github.com/bcho04/galeforce/releases/tag/v0.5.1). See https://github.com/bcho04/galeforce/commit/8636d46d53bfb5625d98bd99a7d1e59a3ff4058f for more details.
